// src/ui/components/BoardList.tsx
import { useState } from 'react';
import type { Board } from '../types';

interface BoardListProps {
  boards: Board[];
  isDarkMode: boolean;
  onSelectBoard: (board: Board) => void;
  onCreateBoard: (name: string, description?: string) => void;
  onDeleteBoard: (id: string) => void;
  onToggleDarkMode: () => void;
  onExport: () => void;
  onImport: () => void;
}

export function BoardList({
  boards,
  isDarkMode,
  onSelectBoard,
  onCreateBoard,
  onDeleteBoard,
  onToggleDarkMode,
  onExport,
  onImport
}: BoardListProps) {
  const [isCreating, setIsCreating] = useState(false);
  const [newBoardName, setNewBoardName] = useState('');
  const [newBoardDescription, setNewBoardDescription] = useState('');
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);

  const handleCreate = () => {
    if (newBoardName.trim()) {
      onCreateBoard(newBoardName.trim(), newBoardDescription.trim() || undefined);
      setNewBoardName('');
      setNewBoardDescription('');
      setIsCreating(false);
    }
  };

  const handleDelete = (id: string) => {
    onDeleteBoard(id);
    setDeleteConfirm(null);
  };

  const bgClass = isDarkMode ? 'bg-gray-900' : 'bg-gray-50';
  const cardBgClass = isDarkMode ? 'bg-gray-800' : 'bg-white';
  const textClass = isDarkMode ? 'text-gray-100' : 'text-gray-900';
  const subTextClass = isDarkMode ? 'text-gray-400' : 'text-gray-600';
  const borderClass = isDarkMode ? 'border-gray-700' : 'border-gray-200';

  return (
    <div className={`min-h-screen ${bgClass} p-8`}>
      {/* Header */}
      <header className="max-w-6xl mx-auto mb-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
              <svg className="w-7 h-7 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2" />
              </svg>
            </div>
            <div>
              <h1 className={`text-2xl font-bold ${textClass}`}>Orbit Board</h1>
              <p className={subTextClass}>Your local kanban board</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            {/* Dark Mode Toggle */}
            <button
              onClick={onToggleDarkMode}
              className={`p-2 rounded-lg ${isDarkMode ? 'bg-gray-800 hover:bg-gray-700' : 'bg-gray-100 hover:bg-gray-200'} transition-colors`}
              title={isDarkMode ? 'Switch to light mode' : 'Switch to dark mode'}
            >
              {isDarkMode ? (
                <svg className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
                </svg>
              ) : (
                <svg className="w-5 h-5 text-gray-600" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
                </svg>
              )}
            </button>

            {/* Export Button */}
            <button
              onClick={onExport}
              className={`p-2 rounded-lg ${isDarkMode ? 'bg-gray-800 hover:bg-gray-700' : 'bg-gray-100 hover:bg-gray-200'} transition-colors`}
              title="Export data"
            >
              <svg className={`w-5 h-5 ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
              </svg>
            </button>

            {/* Import Button */}
            <button
              onClick={onImport}
              className={`p-2 rounded-lg ${isDarkMode ? 'bg-gray-800 hover:bg-gray-700' : 'bg-gray-100 hover:bg-gray-200'} transition-colors`}
              title="Import data"
            >
              <svg className={`w-5 h-5 ${isDarkMode ? 'text-gray-400' : 'text-gray-600'}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
            </button>
          </div>
        </div>
      </header>

      {/* Board Grid */}
      <main className="max-w-6xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {/* Create New Board Card */}
          {isCreating ? (
            <div className={`${cardBgClass} rounded-xl p-6 border ${borderClass}`}>
              <input
                type="text"
                value={newBoardName}
                onChange={(e) => setNewBoardName(e.target.value)}
                placeholder="Board name"
                className={`w-full p-3 rounded-lg mb-3 ${isDarkMode ? 'bg-gray-700 text-white placeholder-gray-400' : 'bg-gray-100 text-gray-900 placeholder-gray-500'}`}
                autoFocus
              />
              <textarea
                value={newBoardDescription}
                onChange={(e) => setNewBoardDescription(e.target.value)}
                placeholder="Description (optional)"
                className={`w-full p-3 rounded-lg mb-4 resize-none ${isDarkMode ? 'bg-gray-700 text-white placeholder-gray-400' : 'bg-gray-100 text-gray-900 placeholder-gray-500'}`}
                rows={2}
              />
              <div className="flex gap-2">
                <button
                  onClick={handleCreate}
                  className="flex-1 bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition-colors"
                >
                  Create Board
                </button>
                <button
                  onClick={() => {
                    setIsCreating(false);
                    setNewBoardName('');
                    setNewBoardDescription('');
                  }}
                  className={`py-2 px-4 rounded-lg ${isDarkMode ? 'text-gray-400 hover:text-gray-200' : 'text-gray-600 hover:text-gray-800'}`}
                >
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <button
              onClick={() => setIsCreating(true)}
              className={`${cardBgClass} rounded-xl p-6 border-2 border-dashed ${borderClass} hover:border-blue-500 transition-colors flex flex-col items-center justify-center gap-3 min-h-[180px]`}
            >
              <div className="w-12 h-12 rounded-full bg-blue-500 bg-opacity-20 flex items-center justify-center">
                <svg className="w-6 h-6 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                </svg>
              </div>
              <span className={`font-medium ${subTextClass}`}>Create new board</span>
            </button>
          )}

          {/* Existing Boards */}
          {boards.map(board => (
            <div
              key={board.id}
              className={`${cardBgClass} rounded-xl p-6 border ${borderClass} hover:shadow-lg transition-shadow cursor-pointer relative group`}
              onClick={() => onSelectBoard(board)}
            >
              {deleteConfirm === board.id ? (
                <div className="absolute inset-0 bg-black bg-opacity-50 rounded-xl flex items-center justify-center z-10">
                  <div className={`${cardBgClass} p-4 rounded-lg shadow-xl`}>
                    <p className={`${textClass} mb-4`}>Delete this board?</p>
                    <div className="flex gap-2">
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDelete(board.id);
                        }}
                        className="flex-1 bg-red-600 text-white py-2 px-4 rounded hover:bg-red-700"
                      >
                        Delete
                      </button>
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          setDeleteConfirm(null);
                        }}
                        className={`py-2 px-4 rounded ${isDarkMode ? 'bg-gray-700 text-gray-300' : 'bg-gray-200 text-gray-700'}`}
                      >
                        Cancel
                      </button>
                    </div>
                  </div>
                </div>
              ) : null}

              <div className="flex items-start justify-between mb-3">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-green-400 to-blue-500 flex items-center justify-center">
                  <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2" />
                  </svg>
                </div>
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    setDeleteConfirm(board.id);
                  }}
                  className={`opacity-0 group-hover:opacity-100 p-2 rounded-lg ${isDarkMode ? 'hover:bg-gray-700' : 'hover:bg-gray-100'} transition-all`}
                >
                  <svg className="w-4 h-4 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                </button>
              </div>

              <h3 className={`font-semibold text-lg mb-2 ${textClass}`}>{board.name}</h3>
              {board.description && (
                <p className={`${subTextClass} text-sm line-clamp-2`}>{board.description}</p>
              )}
              <p className={`mt-4 text-xs ${subTextClass}`}>
                Updated {new Date(board.updated_at).toLocaleDateString()}
              </p>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}

// src/app/components/board-list/board-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { BoardService } from '../../services/board.service';
import { Board } from '../../models';

@Component({
  selector: 'app-board-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './board-list.component.html'
})
export class BoardListComponent implements OnInit {
  showCreateModal = false;
  newBoardName = '';
  newBoardDescription = '';
  boardToDelete: Board | null = null;

  constructor(
    public boardService: BoardService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.boardService.loadBoards();
  }

  openBoard(board: Board): void {
    this.router.navigate(['/board', board.id]);
  }

  openCreateModal(): void {
    this.newBoardName = '';
    this.newBoardDescription = '';
    this.showCreateModal = true;
  }

  closeCreateModal(): void {
    this.showCreateModal = false;
    this.newBoardName = '';
    this.newBoardDescription = '';
  }

  async createBoard(): Promise<void> {
    if (!this.newBoardName.trim()) return;
    
    const board = await this.boardService.createBoard(
      this.newBoardName.trim(),
      this.newBoardDescription.trim() || undefined
    );
    
    if (board) {
      this.closeCreateModal();
      this.router.navigate(['/board', board.id]);
    }
  }

  confirmDelete(board: Board, event: Event): void {
    event.stopPropagation();
    this.boardToDelete = board;
  }

  cancelDelete(): void {
    this.boardToDelete = null;
  }

  async deleteBoard(): Promise<void> {
    if (!this.boardToDelete) return;
    await this.boardService.deleteBoard(this.boardToDelete.id);
    this.boardToDelete = null;
  }

  formatDate(dateString?: string): string {
    if (!dateString) return '';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  }
}

<div class="min-h-screen bg-gray-50 dark:bg-gray-900">
  <div class="max-w-6xl mx-auto px-4 py-8">
    <div class="flex items-center justify-between mb-8">
      <h1 class="text-2xl font-bold text-gray-900 dark:text-white">Your Boards</h1>
      <button
        (click)="openCreateModal()"
        class="flex items-center gap-2 px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg transition-colors"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
        </svg>
        New Board
      </button>
    </div>

    <!-- Board Grid -->
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
      @for (board of boardService.boards$ | async; track board.id) {
        <div
          (click)="openBoard(board)"
          class="group relative bg-white dark:bg-gray-800 rounded-lg shadow-sm hover:shadow-md border border-gray-200 dark:border-gray-700 p-4 cursor-pointer transition-all"
        >
          <div class="flex items-start justify-between mb-2">
            <h3 class="font-semibold text-gray-900 dark:text-white truncate pr-2">{{ board.name }}</h3>
            <button
              (click)="confirmDelete(board, $event)"
              class="opacity-0 group-hover:opacity-100 p-1 text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition-all"
              title="Delete board"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
            </button>
          </div>
          @if (board.description) {
            <p class="text-sm text-gray-500 dark:text-gray-400 line-clamp-2 mb-3">{{ board.description }}</p>
          }
          <p class="text-xs text-gray-400 dark:text-gray-500">Created {{ formatDate(board.created_at) }}</p>
        </div>
      } @empty {
        <div class="col-span-full text-center py-12">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-16 w-16 mx-auto text-gray-300 dark:text-gray-600 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2" />
          </svg>
          <h3 class="text-lg font-medium text-gray-900 dark:text-white mb-2">No boards yet</h3>
          <p class="text-gray-500 dark:text-gray-400 mb-4">Create your first board to get started!</p>
          <button
            (click)="openCreateModal()"
            class="px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg transition-colors"
          >
            Create Board
          </button>
        </div>
      }
    </div>
  </div>
</div>

<!-- Create Board Modal -->
@if (showCreateModal) {
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" (click)="closeCreateModal()">
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-md mx-4 p-6" (click)="$event.stopPropagation()">
      <h2 class="text-xl font-bold text-gray-900 dark:text-white mb-4">Create New Board</h2>
      
      <div class="mb-4">
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Board Name *</label>
        <input
          type="text"
          [(ngModel)]="newBoardName"
          placeholder="Enter board name..."
          class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent"
          (keydown.enter)="createBoard()"
          autofocus
        />
      </div>

      <div class="mb-6">
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">Description (optional)</label>
        <textarea
          [(ngModel)]="newBoardDescription"
          placeholder="Enter description..."
          rows="3"
          class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none"
        ></textarea>
      </div>

      <div class="flex gap-3 justify-end">
        <button
          (click)="closeCreateModal()"
          class="px-4 py-2 text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
        >
          Cancel
        </button>
        <button
          (click)="createBoard()"
          [disabled]="!newBoardName.trim()"
          class="px-4 py-2 bg-primary-600 hover:bg-primary-700 disabled:bg-gray-300 dark:disabled:bg-gray-600 text-white rounded-lg transition-colors"
        >
          Create
        </button>
      </div>
    </div>
  </div>
}

<!-- Delete Confirmation Modal -->
@if (boardToDelete) {
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" (click)="cancelDelete()">
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-sm mx-4 p-6" (click)="$event.stopPropagation()">
      <h2 class="text-xl font-bold text-gray-900 dark:text-white mb-2">Delete Board</h2>
      <p class="text-gray-600 dark:text-gray-400 mb-6">
        Are you sure you want to delete "{{ boardToDelete.name }}"? This action cannot be undone.
      </p>

      <div class="flex gap-3 justify-end">
        <button
          (click)="cancelDelete()"
          class="px-4 py-2 text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
        >
          Cancel
        </button>
        <button
          (click)="deleteBoard()"
          class="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg transition-colors"
        >
          Delete
        </button>
      </div>
    </div>
  </div>
}
