// src/ui/components/CardModal.tsx
import { useState, useEffect } from 'react';
import type { Card, Label } from '../types';

interface CardModalProps {
  card: Card;
  labels: Label[];
  cardLabels: Label[];
  onSave: (card: Card) => void;
  onDelete: (cardId: string) => void;
  onClose: () => void;
  onAddLabel: (cardId: string, labelId: string) => void;
  onRemoveLabel: (cardId: string, labelId: string) => void;
  onCreateLabel: (name: string, color: string) => void;
}

const LABEL_COLORS = [
  '#ef4444', // red
  '#f97316', // orange
  '#eab308', // yellow
  '#22c55e', // green
  '#06b6d4', // cyan
  '#3b82f6', // blue
  '#8b5cf6', // purple
  '#ec4899', // pink
];

export function CardModal({
  card,
  labels,
  cardLabels,
  onSave,
  onDelete,
  onClose,
  onAddLabel,
  onRemoveLabel,
  onCreateLabel,
}: CardModalProps) {
  const [title, setTitle] = useState(card.title);
  const [description, setDescription] = useState(card.description || '');
  const [notes, setNotes] = useState(card.notes || '');
  const [dueDate, setDueDate] = useState(card.due_date || '');
  const [showLabelPicker, setShowLabelPicker] = useState(false);
  const [newLabelName, setNewLabelName] = useState('');
  const [newLabelColor, setNewLabelColor] = useState(LABEL_COLORS[0]);

  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [onClose]);

  const handleSave = () => {
    if (title.trim()) {
      onSave({
        ...card,
        title: title.trim(),
        description: description.trim() || null,
        notes: notes.trim() || null,
        due_date: dueDate || null,
      });
    }
  };

  const handleCreateLabel = () => {
    if (newLabelName.trim()) {
      onCreateLabel(newLabelName.trim(), newLabelColor);
      setNewLabelName('');
    }
  };

  const isLabelAttached = (labelId: string) => {
    return cardLabels.some((l) => l.id === labelId);
  };

  return (
    <div
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
      onClick={onClose}
    >
      <div
        className="bg-white dark:bg-gray-800 rounded-xl shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-6">
          <div className="flex items-start justify-between mb-4">
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              className="flex-1 text-xl font-semibold bg-transparent border-none text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500 rounded px-2 py-1 -ml-2"
              placeholder="Card title"
            />
            <button
              onClick={onClose}
              className="p-2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Labels Section */}
          <div className="mb-6">
            <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Labels</h4>
            <div className="flex flex-wrap gap-2 mb-2">
              {cardLabels.map((label) => (
                <span
                  key={label.id}
                  className="flex items-center gap-1 px-2 py-1 rounded-full text-sm font-medium text-white cursor-pointer hover:opacity-80"
                  style={{ backgroundColor: label.color }}
                  onClick={() => onRemoveLabel(card.id, label.id)}
                  title="Click to remove"
                >
                  {label.name}
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </span>
              ))}
              <button
                onClick={() => setShowLabelPicker(!showLabelPicker)}
                className="px-2 py-1 text-sm text-gray-500 dark:text-gray-400 border border-dashed border-gray-300 dark:border-gray-600 rounded-full hover:border-blue-500 hover:text-blue-500"
              >
                + Add Label
              </button>
            </div>

            {showLabelPicker && (
              <div className="p-3 bg-gray-50 dark:bg-gray-700/50 rounded-lg">
                <div className="space-y-2 mb-3">
                  {labels
                    .filter((l) => !isLabelAttached(l.id))
                    .map((label) => (
                      <button
                        key={label.id}
                        onClick={() => onAddLabel(card.id, label.id)}
                        className="flex items-center gap-2 w-full px-3 py-2 rounded-md hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
                      >
                        <span
                          className="w-4 h-4 rounded-full"
                          style={{ backgroundColor: label.color }}
                        />
                        <span className="text-sm text-gray-700 dark:text-gray-300">{label.name}</span>
                      </button>
                    ))}
                </div>
                <div className="flex gap-2 items-center">
                  <input
                    type="text"
                    value={newLabelName}
                    onChange={(e) => setNewLabelName(e.target.value)}
                    placeholder="New label name"
                    className="flex-1 px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-md bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
                  />
                  <div className="flex gap-1">
                    {LABEL_COLORS.map((color) => (
                      <button
                        key={color}
                        onClick={() => setNewLabelColor(color)}
                        className={`w-6 h-6 rounded-full ${newLabelColor === color ? 'ring-2 ring-offset-2 ring-blue-500 dark:ring-offset-gray-700' : ''}`}
                        style={{ backgroundColor: color }}
                      />
                    ))}
                  </div>
                  <button
                    onClick={handleCreateLabel}
                    className="px-3 py-2 text-sm bg-blue-500 text-white rounded-md hover:bg-blue-600"
                  >
                    Create
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Description */}
          <div className="mb-6">
            <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Description</h4>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Add a more detailed description..."
              className="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white resize-none"
              rows={3}
            />
          </div>

          {/* Due Date */}
          <div className="mb-6">
            <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Due Date</h4>
            <div className="flex items-center gap-2">
              <input
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                className="px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
              />
              {dueDate && (
                <button
                  onClick={() => setDueDate('')}
                  className="p-2 text-gray-400 hover:text-red-500"
                  title="Clear due date"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              )}
            </div>
          </div>

          {/* Notes */}
          <div className="mb-6">
            <h4 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Notes</h4>
            <textarea
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder="Add private notes..."
              className="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white resize-none"
              rows={4}
            />
          </div>

          {/* Actions */}
          <div className="flex items-center justify-between pt-4 border-t border-gray-200 dark:border-gray-700">
            <button
              onClick={() => {
                if (confirm('Delete this card? This cannot be undone.')) {
                  onDelete(card.id);
                }
              }}
              className="px-4 py-2 text-sm text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-md"
            >
              Delete Card
            </button>
            <div className="flex gap-2">
              <button
                onClick={onClose}
                className="px-4 py-2 text-sm text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-md"
              >
                Cancel
              </button>
              <button
                onClick={handleSave}
                className="px-4 py-2 text-sm bg-blue-500 text-white rounded-md hover:bg-blue-600"
              >
                Save Changes
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/app/components/card-modal/card-modal.component.ts
import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, debounceTime, takeUntil } from 'rxjs';
import { Card, Label } from '../../models';
import { BoardService } from '../../services/board.service';

@Component({
  selector: 'app-card-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './card-modal.component.html'
})
export class CardModalComponent implements OnInit, OnDestroy {
  @Input() card!: Card;
  @Input() labels: Label[] = [];
  @Output() close = new EventEmitter<void>();
  @Output() save = new EventEmitter<Card>();
  @Output() delete = new EventEmitter<Card>();

  editedCard!: Card;
  showLabelPicker = false;
  showAddLabel = false;
  newLabelName = '';
  newLabelColor = '#3b82f6';

  private saveSubject = new Subject<void>();
  private destroy$ = new Subject<void>();

  labelColors = [
    '#ef4444', // red
    '#f97316', // orange
    '#eab308', // yellow
    '#22c55e', // green
    '#14b8a6', // teal
    '#3b82f6', // blue
    '#8b5cf6', // violet
    '#ec4899', // pink
    '#6b7280', // gray
  ];

  constructor(private boardService: BoardService) {}

  ngOnInit(): void {
    this.editedCard = { ...this.card };
    
    // Setup autosave with debounce
    this.saveSubject.pipe(
      debounceTime(500),
      takeUntil(this.destroy$)
    ).subscribe(() => {
      this.autoSave();
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  onFieldChange(): void {
    this.saveSubject.next();
  }

  private async autoSave(): Promise<void> {
    await this.boardService.updateCard(this.editedCard);
  }

  async saveAndClose(): Promise<void> {
    this.save.emit(this.editedCard);
    this.close.emit();
  }

  onClose(): void {
    this.close.emit();
  }

  onDelete(): void {
    this.delete.emit(this.card);
    this.close.emit();
  }

  toggleLabelPicker(): void {
    this.showLabelPicker = !this.showLabelPicker;
    this.showAddLabel = false;
  }

  isLabelSelected(label: Label): boolean {
    return this.editedCard.labels?.some(l => l.id === label.id) || false;
  }

  async toggleLabel(label: Label): Promise<void> {
    if (this.isLabelSelected(label)) {
      await this.boardService.removeLabelFromCard(this.card.id, label.id);
      this.editedCard.labels = this.editedCard.labels?.filter(l => l.id !== label.id) || [];
    } else {
      await this.boardService.addLabelToCard(this.card.id, label.id);
      if (!this.editedCard.labels) {
        this.editedCard.labels = [];
      }
      this.editedCard.labels.push(label);
    }
  }

  showAddLabelForm(): void {
    this.showAddLabel = true;
    this.newLabelName = '';
    this.newLabelColor = '#3b82f6';
  }

  cancelAddLabel(): void {
    this.showAddLabel = false;
  }

  async addLabel(): Promise<void> {
    if (!this.newLabelName.trim()) return;
    
    const label = await this.boardService.createLabel(this.newLabelName.trim(), this.newLabelColor);
    if (label) {
      this.labels.push(label);
      await this.boardService.addLabelToCard(this.card.id, label.id);
      if (!this.editedCard.labels) {
        this.editedCard.labels = [];
      }
      this.editedCard.labels.push(label);
    }
    this.showAddLabel = false;
  }
}

<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" (click)="onClose()">
  <div class="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-2xl mx-4 max-h-[90vh] overflow-hidden flex flex-col" (click)="$event.stopPropagation()">
    <!-- Header -->
    <div class="p-4 border-b border-gray-200 dark:border-gray-700 flex items-start justify-between">
      <div class="flex-1 pr-4">
        <input
          type="text"
          [(ngModel)]="editedCard.title"
          (ngModelChange)="onFieldChange()"
          class="w-full text-lg font-semibold text-gray-900 dark:text-white bg-transparent border-0 focus:ring-0 p-0 focus:outline-none"
          placeholder="Card title..."
        />
      </div>
      <button
        (click)="onClose()"
        class="p-1 text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 transition-colors"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
        </svg>
      </button>
    </div>

    <!-- Content -->
    <div class="flex-1 overflow-y-auto p-4">
      <!-- Labels -->
      <div class="mb-6">
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Labels</label>
        <div class="flex flex-wrap gap-2 mb-2">
          @for (label of editedCard.labels; track label.id) {
            <span
              class="px-3 py-1 text-sm font-medium rounded-full text-white cursor-pointer hover:opacity-80"
              [style.backgroundColor]="label.color"
              (click)="toggleLabel(label)"
            >
              {{ label.name }} ×
            </span>
          }
          <button
            (click)="toggleLabelPicker()"
            class="px-3 py-1 text-sm text-gray-600 dark:text-gray-300 border border-dashed border-gray-300 dark:border-gray-600 rounded-full hover:border-primary-500 hover:text-primary-500 transition-colors"
          >
            + Add Label
          </button>
        </div>

        <!-- Label Picker -->
        @if (showLabelPicker) {
          <div class="bg-gray-50 dark:bg-gray-700 rounded-lg p-3 mt-2">
            <div class="flex flex-wrap gap-2 mb-3">
              @for (label of labels; track label.id) {
                <button
                  (click)="toggleLabel(label)"
                  class="flex items-center gap-1 px-3 py-1 text-sm font-medium rounded-full text-white transition-opacity"
                  [style.backgroundColor]="label.color"
                  [class.ring-2]="isLabelSelected(label)"
                  [class.ring-offset-2]="isLabelSelected(label)"
                  [class.ring-gray-900]="isLabelSelected(label)"
                  [class.dark:ring-offset-gray-700]="isLabelSelected(label)"
                >
                  {{ label.name }}
                  @if (isLabelSelected(label)) {
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
                    </svg>
                  }
                </button>
              }
            </div>

            @if (showAddLabel) {
              <div class="space-y-2 border-t border-gray-200 dark:border-gray-600 pt-3">
                <input
                  type="text"
                  [(ngModel)]="newLabelName"
                  placeholder="Label name..."
                  class="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-800 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                  (keydown.enter)="addLabel()"
                />
                <div class="flex gap-2 flex-wrap">
                  @for (color of labelColors; track color) {
                    <button
                      (click)="newLabelColor = color"
                      class="w-6 h-6 rounded-full transition-transform hover:scale-110"
                      [style.backgroundColor]="color"
                      [class.ring-2]="newLabelColor === color"
                      [class.ring-offset-2]="newLabelColor === color"
                      [class.ring-gray-900]="newLabelColor === color"
                    ></button>
                  }
                </div>
                <div class="flex gap-2">
                  <button
                    (click)="addLabel()"
                    [disabled]="!newLabelName.trim()"
                    class="px-3 py-1 text-sm bg-primary-600 hover:bg-primary-700 disabled:bg-gray-300 text-white rounded transition-colors"
                  >
                    Create
                  </button>
                  <button
                    (click)="cancelAddLabel()"
                    class="px-3 py-1 text-sm text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 rounded transition-colors"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            } @else {
              <button
                (click)="showAddLabelForm()"
                class="text-sm text-primary-600 dark:text-primary-400 hover:underline"
              >
                Create new label
              </button>
            }
          </div>
        }
      </div>

      <!-- Due Date -->
      <div class="mb-6">
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Due Date</label>
        <input
          type="date"
          [(ngModel)]="editedCard.due_date"
          (ngModelChange)="onFieldChange()"
          class="px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent"
        />
      </div>

      <!-- Description -->
      <div class="mb-6">
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Description</label>
        <textarea
          [(ngModel)]="editedCard.description"
          (ngModelChange)="onFieldChange()"
          placeholder="Add a more detailed description..."
          rows="4"
          class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none"
        ></textarea>
      </div>

      <!-- Notes -->
      <div class="mb-6">
        <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Notes</label>
        <textarea
          [(ngModel)]="editedCard.notes"
          (ngModelChange)="onFieldChange()"
          placeholder="Add private notes..."
          rows="3"
          class="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none"
        ></textarea>
      </div>
    </div>

    <!-- Footer -->
    <div class="p-4 border-t border-gray-200 dark:border-gray-700 flex items-center justify-between">
      <button
        (click)="onDelete()"
        class="px-4 py-2 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-colors"
      >
        Delete Card
      </button>
      <div class="flex gap-2">
        <span class="text-sm text-gray-500 dark:text-gray-400 self-center mr-2">Auto-saved</span>
        <button
          (click)="saveAndClose()"
          class="px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg transition-colors"
        >
          Done
        </button>
      </div>
    </div>
  </div>
</div>
