// src/app/components/column/column.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CdkDragDrop, CdkDropList, CdkDrag } from '@angular/cdk/drag-drop';
import { Column, Card } from '../../models';
import { CardComponent } from '../card/card.component';

@Component({
  selector: 'app-column',
  standalone: true,
  imports: [CommonModule, FormsModule, CdkDropList, CdkDrag, CardComponent],
  templateUrl: './column.component.html'
})
export class ColumnComponent {
  @Input() column!: Column;
  @Input() connectedLists: string[] = [];
  @Output() cardDrop = new EventEmitter<CdkDragDrop<Card[]>>();
  @Output() cardClick = new EventEmitter<Card>();
  @Output() cardDelete = new EventEmitter<Card>();
  @Output() cardCreate = new EventEmitter<{ columnId: string; title: string }>();
  @Output() columnUpdate = new EventEmitter<Column>();
  @Output() columnDelete = new EventEmitter<Column>();

  isEditing = false;
  editName = '';
  showAddCard = false;
  newCardTitle = '';

  startEditing(): void {
    this.editName = this.column.name;
    this.isEditing = true;
  }

  saveEdit(): void {
    if (this.editName.trim() && this.editName !== this.column.name) {
      this.columnUpdate.emit({ ...this.column, name: this.editName.trim() });
    }
    this.isEditing = false;
  }

  cancelEdit(): void {
    this.isEditing = false;
    this.editName = '';
  }

  deleteColumn(): void {
    this.columnDelete.emit(this.column);
  }

  showAddCardForm(): void {
    this.showAddCard = true;
    this.newCardTitle = '';
  }

  addCard(): void {
    if (!this.newCardTitle.trim()) return;
    this.cardCreate.emit({ columnId: this.column.id, title: this.newCardTitle.trim() });
    this.newCardTitle = '';
    this.showAddCard = false;
  }

  cancelAddCard(): void {
    this.showAddCard = false;
    this.newCardTitle = '';
  }

  onCardDrop(event: CdkDragDrop<Card[]>): void {
    this.cardDrop.emit(event);
  }

  onCardClick(card: Card): void {
    this.cardClick.emit(card);
  }

  onCardDelete(card: Card): void {
    this.cardDelete.emit(card);
  }
}

<div class="flex flex-col bg-gray-100 dark:bg-gray-800 rounded-lg w-72 shrink-0 max-h-full">
  <!-- Column Header -->
  <div class="p-3 flex items-center justify-between border-b border-gray-200 dark:border-gray-700">
    @if (isEditing) {
      <div class="flex-1 flex items-center gap-2">
        <input
          type="text"
          [(ngModel)]="editName"
          class="flex-1 px-2 py-1 text-sm border border-gray-300 dark:border-gray-600 rounded bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent"
          (keydown.enter)="saveEdit()"
          (keydown.escape)="cancelEdit()"
          (blur)="saveEdit()"
          autofocus
        />
      </div>
    } @else {
      <h3
        class="font-semibold text-gray-800 dark:text-gray-200 cursor-pointer hover:text-primary-600 dark:hover:text-primary-400"
        (click)="startEditing()"
        title="Click to edit"
      >
        {{ column.name }}
      </h3>
    }
    
    <div class="flex items-center gap-1">
      <span class="text-xs text-gray-500 dark:text-gray-400 bg-gray-200 dark:bg-gray-700 px-2 py-0.5 rounded-full">
        {{ column.cards?.length || 0 }}
      </span>
      <button
        (click)="deleteColumn()"
        class="p-1 text-gray-400 hover:text-red-500 dark:hover:text-red-400 transition-colors"
        title="Delete column"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      </button>
    </div>
  </div>

  <!-- Cards List -->
  <div
    cdkDropList
    [id]="column.id"
    [cdkDropListData]="column.cards || []"
    [cdkDropListConnectedTo]="connectedLists"
    (cdkDropListDropped)="onCardDrop($event)"
    class="flex-1 overflow-y-auto p-2 space-y-2 min-h-[100px]"
  >
    @for (card of column.cards; track card.id) {
      <div cdkDrag [cdkDragData]="card">
        <app-card
          [card]="card"
          (cardClick)="onCardClick($event)"
          (deleteClick)="onCardDelete($event)"
        ></app-card>
      </div>
    }
  </div>

  <!-- Add Card Section -->
  <div class="p-2 border-t border-gray-200 dark:border-gray-700">
    @if (showAddCard) {
      <div class="space-y-2">
        <textarea
          [(ngModel)]="newCardTitle"
          placeholder="Enter card title..."
          rows="2"
          class="w-full px-3 py-2 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500 focus:border-transparent resize-none"
          (keydown.enter)="$event.preventDefault(); addCard()"
          (keydown.escape)="cancelAddCard()"
          autofocus
        ></textarea>
        <div class="flex gap-2">
          <button
            (click)="addCard()"
            [disabled]="!newCardTitle.trim()"
            class="px-3 py-1 text-sm bg-primary-600 hover:bg-primary-700 disabled:bg-gray-300 dark:disabled:bg-gray-600 text-white rounded transition-colors"
          >
            Add Card
          </button>
          <button
            (click)="cancelAddCard()"
            class="px-3 py-1 text-sm text-gray-600 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-700 rounded transition-colors"
          >
            Cancel
          </button>
        </div>
      </div>
    } @else {
      <button
        (click)="showAddCardForm()"
        class="w-full flex items-center gap-1 px-3 py-2 text-sm text-gray-600 dark:text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg transition-colors"
      >
        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4v16m8-8H4" />
        </svg>
        Add a card
      </button>
    }
  </div>
</div>

// src/ui/components/Column.tsx
import { useState, useRef } from 'react';
import type { Column as ColumnType, Card, Label } from '../types';
import { CardComponent } from './Card';

interface ColumnProps {
  column: ColumnType;
  cards: Card[];
  labels: Label[];
  cardLabels: Map<string, Label[]>;
  isDarkMode: boolean;
  onUpdateColumn: (column: ColumnType) => void;
  onDeleteColumn: (id: string) => void;
  onCreateCard: (columnId: string, title: string) => void;
  onUpdateCard: (card: Card) => void;
  onDeleteCard: (id: string) => void;
  onAddLabel: (cardId: string, labelId: string) => void;
  onRemoveLabel: (cardId: string, labelId: string) => void;
  onCardDragStart: (e: React.DragEvent, cardId: string, columnId: string) => void;
  onCardDragEnd: () => void;
  onCardDrop: (columnId: string, position: number) => void;
  onColumnDragStart: (e: React.DragEvent, columnId: string) => void;
  onColumnDragEnd: () => void;
  onColumnDrop: (position: number) => void;
  draggedCardId: string | null;
  draggedColumnId: string | null;
}

export function ColumnComponent({
  column,
  cards,
  labels,
  cardLabels,
  isDarkMode,
  onUpdateColumn,
  onDeleteColumn,
  onCreateCard,
  onUpdateCard,
  onDeleteCard,
  onAddLabel,
  onRemoveLabel,
  onCardDragStart,
  onCardDragEnd,
  onCardDrop,
  onColumnDragStart,
  onColumnDragEnd,
  onColumnDrop,
  draggedCardId,
  draggedColumnId
}: ColumnProps) {
  const [isEditingTitle, setIsEditingTitle] = useState(false);
  const [editTitle, setEditTitle] = useState(column.name);
  const [isAddingCard, setIsAddingCard] = useState(false);
  const [newCardTitle, setNewCardTitle] = useState('');
  const [dropIndex, setDropIndex] = useState<number | null>(null);
  const columnRef = useRef<HTMLDivElement>(null);

  const sortedCards = [...cards].sort((a, b) => a.position - b.position);

  const handleSaveTitle = () => {
    if (editTitle.trim()) {
      onUpdateColumn({ ...column, name: editTitle.trim() });
    } else {
      setEditTitle(column.name);
    }
    setIsEditingTitle(false);
  };

  const handleAddCard = () => {
    if (newCardTitle.trim()) {
      onCreateCard(column.id, newCardTitle.trim());
      setNewCardTitle('');
      setIsAddingCard(false);
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    if (draggedCardId) {
      const target = e.currentTarget as HTMLElement;
      const rect = target.getBoundingClientRect();
      const y = e.clientY - rect.top;
      const cardHeight = 80;
      const index = Math.min(Math.floor(y / cardHeight), sortedCards.length);
      setDropIndex(index);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    if (draggedCardId && dropIndex !== null) {
      onCardDrop(column.id, dropIndex);
    }
    setDropIndex(null);
  };

  const handleDragLeave = () => {
    setDropIndex(null);
  };

  const bgClass = isDarkMode ? 'bg-gray-800' : 'bg-gray-100';
  const textClass = isDarkMode ? 'text-gray-100' : 'text-gray-900';
  const headerBgClass = isDarkMode ? 'bg-gray-700' : 'bg-gray-200';

  return (
    <div
      ref={columnRef}
      draggable={!isEditingTitle && !isAddingCard}
      onDragStart={(e) => onColumnDragStart(e, column.id)}
      onDragEnd={onColumnDragEnd}
      onDragOver={(e) => {
        e.preventDefault();
        if (draggedColumnId && draggedColumnId !== column.id) {
          onColumnDrop(column.position);
        }
      }}
      className={`${bgClass} rounded-lg w-72 flex-shrink-0 flex flex-col max-h-full ${
        draggedColumnId === column.id ? 'opacity-50' : ''
      }`}
    >
      {/* Column Header */}
      <div className={`${headerBgClass} rounded-t-lg p-3 cursor-grab`}>
        <div className="flex items-center justify-between">
          {isEditingTitle ? (
            <input
              type="text"
              value={editTitle}
              onChange={(e) => setEditTitle(e.target.value)}
              onBlur={handleSaveTitle}
              onKeyDown={(e) => e.key === 'Enter' && handleSaveTitle()}
              className={`flex-1 p-1 rounded text-sm ${isDarkMode ? 'bg-gray-800 text-white' : 'bg-white text-gray-900'}`}
              autoFocus
            />
          ) : (
            <h3
              className={`font-semibold ${textClass} cursor-pointer flex-1`}
              onClick={() => setIsEditingTitle(true)}
            >
              {column.name}
            </h3>
          )}
          <div className="flex items-center gap-2 ml-2">
            <span className={`text-xs ${isDarkMode ? 'text-gray-400' : 'text-gray-500'}`}>
              {cards.length}
            </span>
            <button
              onClick={() => onDeleteColumn(column.id)}
              className={`p-1 rounded hover:bg-opacity-20 hover:bg-red-500 ${isDarkMode ? 'text-gray-400' : 'text-gray-500'}`}
              title="Delete column"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      </div>

      {/* Cards Container */}
      <div
        className="flex-1 overflow-y-auto p-2 space-y-2 min-h-[100px]"
        onDragOver={handleDragOver}
        onDrop={handleDrop}
        onDragLeave={handleDragLeave}
      >
        {sortedCards.map((card, index) => (
          <div key={card.id}>
            {/* Drop indicator */}
            {dropIndex === index && draggedCardId && (
              <div className="h-1 bg-blue-500 rounded my-1" />
            )}
            <CardComponent
              card={card}
              labels={cardLabels.get(card.id) || []}
              allLabels={labels}
              isDarkMode={isDarkMode}
              onUpdate={onUpdateCard}
              onDelete={onDeleteCard}
              onAddLabel={onAddLabel}
              onRemoveLabel={onRemoveLabel}
              onDragStart={onCardDragStart}
              onDragEnd={onCardDragEnd}
            />
          </div>
        ))}
        {/* Drop indicator at end */}
        {dropIndex === sortedCards.length && draggedCardId && (
          <div className="h-1 bg-blue-500 rounded my-1" />
        )}
      </div>

      {/* Add Card Section */}
      <div className="p-2 border-t border-opacity-20" style={{ borderColor: isDarkMode ? '#4B5563' : '#E5E7EB' }}>
        {isAddingCard ? (
          <div className="space-y-2">
            <textarea
              value={newCardTitle}
              onChange={(e) => setNewCardTitle(e.target.value)}
              placeholder="Enter card title..."
              className={`w-full p-2 rounded border resize-none text-sm ${
                isDarkMode ? 'bg-gray-700 border-gray-600 text-white placeholder-gray-400' : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500'
              }`}
              rows={2}
              autoFocus
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault();
                  handleAddCard();
                }
                if (e.key === 'Escape') {
                  setIsAddingCard(false);
                  setNewCardTitle('');
                }
              }}
            />
            <div className="flex gap-2">
              <button
                onClick={handleAddCard}
                className="flex-1 bg-blue-600 text-white py-1 px-3 rounded text-sm hover:bg-blue-700 transition-colors"
              >
                Add Card
              </button>
              <button
                onClick={() => {
                  setIsAddingCard(false);
                  setNewCardTitle('');
                }}
                className={`py-1 px-3 rounded text-sm ${
                  isDarkMode ? 'text-gray-400 hover:text-gray-200' : 'text-gray-600 hover:text-gray-800'
                }`}
              >
                Cancel
              </button>
            </div>
          </div>
        ) : (
          <button
            onClick={() => setIsAddingCard(true)}
            className={`w-full p-2 rounded text-sm flex items-center gap-2 ${
              isDarkMode 
                ? 'text-gray-400 hover:bg-gray-700 hover:text-gray-200' 
                : 'text-gray-600 hover:bg-gray-200 hover:text-gray-800'
            } transition-colors`}
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
            Add a card
          </button>
        )}
      </div>
    </div>
  );
}
